version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: investco-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investco_db
    ports: ["3307:3306"]
    volumes: [ "dbdata:/var/lib/mysql" ]
  web:
    build: .
    container_name: investco-web
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: investco_db
      MOCK_DB: "0"
    depends_on: [ "db" ]
    ports: [ "8088:8080" ]
volumes: { dbdata: {} }
